import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
  index('app/routes/_index.tsx'),
  route('about', 'app/routes/about.tsx'),
  route('abilities', 'app/routes/abilities.tsx'),
  route('balance-patch', 'app/routes/balance-patch.tsx'),
  route('blog', 'app/routes/blog.tsx'),
  route('blog/:slug', 'app/routes/blog.$slug.tsx'),
  route('classes', 'app/routes/classes.tsx'),
  route('factions', 'app/routes/factions.tsx'),
  route('factions/:id', 'app/routes/factions.$id.tsx'),
  route('heroes', 'app/routes/heroes.tsx'),
  route('heroes/:id', 'app/routes/heroes.$id.tsx'),
  route('items', 'app/routes/items.tsx'),
  route('items/:id', 'app/routes/items.$id.tsx'),
  route('locations', 'app/routes/locations.tsx'),
  route('locations/:id', 'app/routes/locations.$id.tsx'),
  route('monsters', 'app/routes/monsters.tsx'),
  route('monsters/:id', 'app/routes/monsters.$id.tsx'),
  route('news', 'app/routes/news.tsx'),
  route('news/:slug', 'app/routes/news.$slug.tsx'),
  route('npcs', 'app/routes/npcs.tsx'),
  route('npcs/:id', 'app/routes/npcs.$id.tsx'),
  route('parties', 'app/routes/parties.tsx'),
  route('parties/:id', 'app/routes/parties.$id.tsx'),
  route('quests', 'app/routes/quests.tsx'),
  route('quests/:id', 'app/routes/quests.$id.tsx'),
  route('regions', 'app/routes/regions.tsx'),
  route('regions/:id', 'app/routes/regions.$id.tsx'),
  route('search', 'app/routes/search.tsx'),
] satisfies RouteConfig;
